
name: Master build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version
        shell: bash
        run: |
          VERSION=${{ github.sha }}
          VERSION=${VERSION:0:7}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: maxsurm/mystickcounter:${{ env.VERSION }}, maxsurm/mystickcounter:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: mystickcounter
          stack-definition: ${{ github.workspace }}/docker-compose.yml
          image: maxsurm/mystickcounter:${{ env.VERSION }}